// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestGr4d3.DAL.Contexto;

namespace TestGr4d3.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190722143644_ExamenM")]
    partial class ExamenM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestGr4d3.BOL.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadaEn");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("TestGr4d3.BOL.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Feedback");

                    b.HasKey("Id");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("TestGr4d3.BOL.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Curso");

                    b.Property<int>("Edad");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TestGr4d3.BOL.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<int?>("AsignaturaId");

                    b.Property<int?>("CalificacionId");

                    b.Property<string>("Comentario");

                    b.Property<int?>("EstudianteId");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("CalificacionId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("TestGr4d3.BOL.Examen", b =>
                {
                    b.HasOne("TestGr4d3.BOL.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");

                    b.HasOne("TestGr4d3.BOL.Calificacion", "Calificacion")
                        .WithMany()
                        .HasForeignKey("CalificacionId");

                    b.HasOne("TestGr4d3.BOL.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId");
                });
#pragma warning restore 612, 618
        }
    }
}
